// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// hello //
// ----- //

#define hello_wrap_target 2
#define hello_wrap 10

static const uint16_t hello_program_instructions[] = {
    0x80a0, //  0: pull   block                      
    0xa027, //  1: mov    x, osr                     
            //     .wrap_target
    0x80a0, //  2: pull   block                      
    0xe001, //  3: set    pins, 1                    
    0xa027, //  4: mov    x, osr                     
    0xa047, //  5: mov    y, osr                     
    0x0068, //  6: jmp    !y, 8                      
    0x0987, //  7: jmp    y--, 7                 [9] 
    0xe000, //  8: set    pins, 0                    
    0xa047, //  9: mov    y, osr                     
    0x098a, // 10: jmp    y--, 10                [9] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hello_program = {
    .instructions = hello_program_instructions,
    .length = 11,
    .origin = -1,
};

static inline pio_sm_config hello_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hello_wrap_target, offset + hello_wrap);
    return c;
}
#endif

