// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// pindirtest //
// ---------- //

#define pindirtest_wrap_target 0
#define pindirtest_wrap 2

static const uint16_t pindirtest_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0                    
    0xe080, //  1: set    pindirs, 0                 
    0x0002, //  2: jmp    2                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pindirtest_program = {
    .instructions = pindirtest_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config pindirtest_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pindirtest_wrap_target, offset + pindirtest_wrap);
    return c;
}
#endif

